// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace EmployeeSentimentModel.ConsoleApp
{
    public partial class EmployeeSentimentModel
    {
        /// <summary>
        /// model input class for EmployeeSentimentModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"id")]
            public float Id { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"person_name")]
            public string Person_name { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"nine_box_category")]
            public string Nine_box_category { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"feedback")]
            public string Feedback { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"adjusted")]
            public string Adjusted { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"reviewed")]
            public string Reviewed { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"label")]
            public string Label { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"feedback_len")]
            public string Feedback_len { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"num_of_sent")]
            public string Num_of_sent { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"performance_class")]
            public string Performance_class { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"potential_class")]
            public float Potential_class { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"data_type")]
            public float Data_type { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for EmployeeSentimentModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"person_name")]
            public float[] Person_name { get; set; }

            [ColumnName(@"nine_box_category")]
            public uint Nine_box_category { get; set; }

            [ColumnName(@"feedback")]
            public float[] Feedback { get; set; }

            [ColumnName(@"adjusted")]
            public float[] Adjusted { get; set; }

            [ColumnName(@"reviewed")]
            public float[] Reviewed { get; set; }

            [ColumnName(@"label")]
            public float[] Label { get; set; }

            [ColumnName(@"feedback_len")]
            public float[] Feedback_len { get; set; }

            [ColumnName(@"num_of_sent")]
            public float[] Num_of_sent { get; set; }

            [ColumnName(@"performance_class")]
            public float[] Performance_class { get; set; }

            [ColumnName(@"potential_class")]
            public float Potential_class { get; set; }

            [ColumnName(@"data_type")]
            public float Data_type { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("EmployeeSentimentModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("nine_box_category");
            if (labelColumn == null)
            {
                throw new Exception("nine_box_category column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
